version: 2.1

jobs:
  # front
  front_js:
    docker:
      - image: node:8.9
    working_directory: ~/project
    steps:
      - run:
          name: Install yarn dependencies
          command: yarn install
      # - save_cache:
      #   name: Save yarn node modules
      #   key: yarn-v1-{{ checksum "yarn.lock" }}
      #   paths:
      #     - node_modules
      #     - ~/.cache/yarn
      - run:
          name: JS lint
          command: yarn js-lint
    
    # steps:
    #   - run:
    #       name: Install yarn dependencies
    #       command: yarn install
    #   - run:
    #       name: JS lint
    #       command: yarn js-lint

workflows:
  version: 2
  # Commit CI
  test:
    jobs:
      # Step 1: lint tests
      - front_js
  