version: 2
references:
  # Project
  jslint: &jslint
    run:
      name: JS lint
      command: yarn js-lint

  yarn_install: &yarn_install
    run:
      name: Install yarn dependencies
      command: yarn install

  # Jobs
  job_js: &job_js
    steps:
      - checkout:
          path: ~/project
            - *yarn_install
            - *jslint

jobs:
  # front
  front_js:
    docker:
      - image: node:8.9
    working_directory: ~/project
    # <<: *job_js
    steps:
      - run:
          name: JS lint
          command: yarn js-lint
      - run:
          name: Install yarn dependencies
          command: yarn install

workflows:
  version: 2
  # Commit CI
  test:
    jobs:
      # Step 1: lint tests
      - front_js
  