version: 2.1

jobs:
  # front
  front_js:
    docker:
      - image: node:8.9
    working_directory: ~/
    steps:
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run: ls -l
      - run:
          name: JS lint
          command: yarn js-lint


workflows:
  version: 2
  # Commit CI
  test:
    jobs:
      # Step 1: lint tests
      - front_js
  