version: 2
references:
  # Project
  jslint: &jslint
    run:
      name: JS lint
      command: yarn js-lint

  yarn_install: &yarn_install
    run:
      name: Install yarn dependencies
      command: yarn install
  
  # yarn_save: &yarn_save
  #   save_cache:
  #     name: Save yarn node modules
  #     key: yarn-v1-{{ checksum "yarn.lock" }}
  #     paths:
  #       - node_modules
  #       - ~/.cache/yarn
  
  # yarn_restore: &yarn_restore
  #   restore_cache:
  #     name: Restore yarn node modules
  #     keys:
  #       - yarn-v1-{{ checksum "yarn.lock" }}

  # Jobs
  job_js: &job_js
    steps:
        - checkout:
            path: ~/project/src
              - *yarn_install
              - *jslint

jobs:
  # front
  front_js:
    docker:
      - image: node:8.9
    working_directory: ~/project
    <<: *job_js

workflows:
  version: 2
  # Commit CI
  test:
    jobs:
      # Step 1: lint tests
      - front_js
  
  
  deploy:
    jobs:
      - front_js:
          filters:
            branches:
              only: master