version: 2.1

jobs:
  # front
  front_js:
    docker:
      - image: node:8.9
    steps:
      - checkout 
      - run:
          name: Install node
          command: npm install node
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: JS lint
          command: yarn js-lint


workflows:
  version: 2
  # Commit CI
  test:
    jobs:
      # Step 1: lint tests
      - front_js
  